### ISSUE TITLE
ddmc 喂鱼有点问题 跑不了了

### ISSUE THREAD

**Issue by kkkkxl** [lksky8/sign-ql#3]
![image](https://user-images.githubusercontent.com/37541028/192196950-1dc06e79-73e0-46f1-9b13-b9f2184ebbb6.png)
![1664168245073](https://user-images.githubusercontent.com/37541028/192196956-841eb93d-7cbe-44f0-9df6-c25df34e6073.jpg)

data返回是个  空白

**Comment by lksky8** [comment]
嗯，我更新了，这是软件那边问题，偶尔喂不了鱼，喂不了鱼我直接跳过了，这种问题处理不了，只能看程序员什么时候修复好

**Comment by kkkkxl** [comment]
> 嗯，我更新了，这是软件那边问题，偶尔喂不了鱼，喂不了鱼我直接跳过了，这种问题处理不了，只能看程序员什么时候修复好

ok
