### ISSUE TITLE
统一茄皇

### ISSUE THREAD

**Issue by charleyyy** [lksky8/sign-ql#8]
获取AU失败，请检查你的变量是否正确
设置了环境变量也是这样 不知道是不是设置错误了 
看了脚本注释，环境变量设置了UA AU都不行 求大家伙了

**Comment by lksky8** [comment]
获取的参数是抓包：https://apig.xiaoyisz.com/qiehuang/ga/public/api/login 这个包里面是请求数据，然后放到青龙配置文件。export tybody='{"appId":"wx532ecb3bdaaf92f9","openId":"oBXXXXm9Fnmjp8pqFw4nD-ZzdcZY","wid":XXXX,"signature":"XXXXXXXXXXXXXXXXXXXXXXX"}'

**Comment by lksky8** [comment]
检查下有没有问题

**Comment by charleyyy** [comment]
非常感谢!!成功了，之前stream抓的这几个一直顺序搞错了
感谢回复

**Comment by charleyyy** [comment]
> 非常感谢!!成功了，之前stream抓的这几个一直顺序搞错了
> 感谢回复
